include "src/gp";
include "src/GC";
include "src/Collection";
include "src/TopoDS";
include "src/BRepBuilderAPI";

open gp;
open Collection;
open GC;
open Geom;
open BRepBuilderAPI;
open TopoDS;

var w = 50.0;
var h = 70.0;
var t = 30.0;

var p1 = Pnt( -w / 2.0, 0.0, 0.0);
var p2 = Pnt( -w / 2.0, -t / 4.0, 0.0);
var p3 = Pnt(0.0, -t / 2.0, 0.0);
var p4 = Pnt( w / 2.0, -t / 4.0, 0.0);
var p5 = Pnt( w / 2.0, 0.0, 0.0);

var aoc = arcOfCircle ( p2, p3, p4);
var seg1    = segment ( p1, p2);
var seg2    = segment ( p4, p5);

var edge1 = edge seg1;
var edge2 = edge aoc;
var edge3 = edge seg2;
var wir = wire ( edge1, edge2, edge3);

println$ "X=" + str( p1.x ) + " Y=" + str( p1.y ) + " Z=" + str( p1.z );

open Array1[int];

var a1 = Array1[int]::createH(0,3);
//var s = a1.length;
//println$ "a1.Size=" + str( s );

var seg = segment (p1, p2);

println$ "Trimmed curve, start=" + seg.startPoint.x.str + ", end=" + seg.endPoint.x.str;
// if s.IsDone do
//   var c = s.Value;
//   println$ "got trimmed Curve";
// else
//   var e = s.Status;
//   println$ "got Error" + str( e);
// done


